import os.path

LOADFLOW_SCENARIOS = [
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_e_mob_with_pv_bat", "av_e_mob_with_pv_bat_0_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_e_mob_with_pv_bat", "av_e_mob_with_pv_bat_20_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_e_mob_with_pv_bat", "av_e_mob_with_pv_bat_40_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_e_mob_with_pv_bat", "av_e_mob_with_pv_bat_60_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_e_mob_with_pv_bat", "av_e_mob_with_pv_bat_80_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_e_mob_with_pv_bat", "av_e_mob_with_pv_bat_100_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_heat_pump", "av_heat_pump_0_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_heat_pump", "av_heat_pump_20_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_heat_pump", "av_heat_pump_40_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_heat_pump", "av_heat_pump_60_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_heat_pump", "av_heat_pump_80_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_heat_pump", "av_heat_pump_100_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_hyb", "av_hyb_0_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_hyb", "av_hyb_20_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_hyb", "av_hyb_40_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_hyb", "av_hyb_60_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_hyb", "av_hyb_80_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_hyb", "av_hyb_100_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_hyb_with_pv_bat", "av_hyb_with_pv_bat_0_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_hyb_with_pv_bat", "av_hyb_with_pv_bat_20_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_hyb_with_pv_bat", "av_hyb_with_pv_bat_40_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_hyb_with_pv_bat", "av_hyb_with_pv_bat_60_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_hyb_with_pv_bat", "av_hyb_with_pv_bat_80_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_hyb_with_pv_bat", "av_hyb_with_pv_bat_100_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_pv", "av_pv_0_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_pv", "av_pv_20_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_pv", "av_pv_40_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_pv", "av_pv_60_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_pv", "av_pv_80_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_pv", "av_pv_100_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_pv_bat", "av_pv_bat_0_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_pv_bat", "av_pv_bat_20_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_pv_bat", "av_pv_bat_40_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_pv_bat", "av_pv_bat_60_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_pv_bat", "av_pv_bat_80_altbau_HR.xlsx")),
    os.path.abspath(os.path.join(str(os.path.dirname(__file__)), "03_monte_carlo", "Altbau_av_pv_bat", "av_pv_bat_100_altbau_HR.xlsx"))
]
